### ISSUE TITLE
无法下载需要登录的内容

### ISSUE THREAD

**Issue by Lin-Guanguo** [hect0x7/JMComic-Crawler-Python#104]
配置里配 cookies, 还是在程序里手动调用 login. 都不太行

代码没看出问题来. 调试发现一些现象.

访问的网址是https://jm-comic2.club/album/400511, 返回的url是 https://18comic.vip/error/album_missing, 不知道和这个重定向有没有关系. 加了AVS cookies 不生效.
login方法似乎从来没有成功过, 返回是301.  ('location', 'https://18comic.vip/login').

**Comment by hect0x7** [comment]
贴一下你的配置文件，我感觉有概率是cookies的配置不对

**Comment by hect0x7** [comment]
我测试了下，配置了AVS就可以获取到了
```
2023-08-27 20:03:05:【html】https://18comic.vip/album/400511
[一只麻利的鸽子汉化] [半里プラザー (半里バード)] 便器聖女ブランカ [DL版]
```

**Comment by hect0x7** [comment]
至于login，禁漫登录成功就是返回301
![image](https://github.com/hect0x7/JMComic-Crawler-Python/assets/93357912/7a473686-e721-4a69-8f97-c201a85c6428)

**Comment by hect0x7** [comment]
登录也可以获取成功
```python
from jmcomic import *

option = create_option('xxx')
client = option.build_jm_client()

client.login('xxx', 'yyy')
album = client.get_album_detail('400511')
print(album.title)
```

输出
```
2023-08-27 20:07:19:【html】https://18comic.vip/login
2023-08-27 20:07:19:【html】https://18comic.vip/album/400511
[一只麻利的鸽子汉化] [半里プラザー (半里バード)] 便器聖女ブランカ [DL版]
```

**Comment by Lin-Guanguo** [comment]
这是我的运行脚本和输出结果. 不确定和我使用了代理这点有没有关系

```py
import os
import sys
import jmcomic  # 导入此模块，需要先安装.

def get_option():
    option = jmcomic.JmOption.construct({
        'client': {
            'postman': {
                'meta_data': {
                    'proxies': jmcomic.ProxyBuilder.v2ray_proxy(),
                    'cookies': {
                        'AVS': 'ho313fkudhdocgh8m6flp43ehr'
                    }
                }
            }
        },
        'dir_rule': {
            'base_dir': './download',
            'rule': os.environ.get('DIR_RULE', 'Bd_Aauthor_Atitle_Pindextitle')
        },
        'download': {
            'threading': {
                'batch_count': int(os.environ.get('BATCH_COUNT', 10))
            }
        }
    })

    return option

jm_option = get_option()
jmcomic.download_album([400511], option=jm_option)
```

```
023-08-28 22:52:19:【获取禁漫URL】[https://jm365.work/3YeBdF] → [https://jm-comic2.club]
2023-08-28 22:52:19:【html】https://jm-comic2.club/album/400511
2023-08-28 22:52:26:【dler.exception】JmDownloader Exit with exception: (<class 'jmcomic.jm_config.JmcomicException'>, JmcomicException('请求的本子不存在！(/album/400511)\n原因可能为:\n1. id有误，检查你的本子/章节id\n2. 该漫画只对登录用户可见，请配置你的cookies\n'))
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/lighthouse/dev/JMComic-Crawler-Python/src/jmcomic/api.py", line 26, in <lambda>
    apply_each_obj_func=lambda aid: download_api(aid, option),
  File "/home/lighthouse/dev/JMComic-Crawler-Python/src/jmcomic/api.py", line 42, in download_album
    dler.download_album(jm_album_id)
  File "/home/lighthouse/dev/JMComic-Crawler-Python/src/jmcomic/jm_downloader.py", line 68, in download_album
    album = client.get_album_detail(album_id)
  File "/home/lighthouse/.local/lib/python3.8/site-packages/common/util/decorator_util.py", line 67, in __call__
    value = self.invoke(args, kwargs)
  File "/home/lighthouse/.local/lib/python3.8/site-packages/common/util/decorator_util.py", line 55, in invoke
    return self.func(*args, **kwargs)
  File "/home/lighthouse/dev/JMComic-Crawler-Python/src/jmcomic/jm_client_impl.py", line 157, in get_album_detail
    resp = self.get_jm_html(f"/album/{album_id}")
  File "/home/lighthouse/dev/JMComic-Crawler-Python/src/jmcomic/jm_client_impl.py", line 238, in get_jm_html
    self.require_resp_success_else_raise(resp, url)
  File "/home/lighthouse/dev/JMComic-Crawler-Python/src/jmcomic/jm_client_impl.py", line 317, in require_resp_success_else_raise
    cls.raise_request_error(
  File "/home/lighthouse/dev/JMComic-Crawler-Python/src/jmcomic/jm_client_impl.py", line 254, in raise_request_error
    raise JmModuleConfig.exception(msg)
jmcomic.jm_config.JmcomicException: 请求的本子不存在！(/album/400511)
原因可能为:
1. id有误，检查你的本子/章节id
2. 该漫画只对登录用户可见，请配置你的cookies
```

**Comment by hect0x7** [comment]
> 确实和代理有关. 代理一关就好了. 一开就坏, 复现相当稳定.

也许是因为AVS里包含了ip信息，而代理的ip和AVS的ip不一致，会判定为登录无效

**Comment by hect0x7** [comment]
你试试如下步骤：
1. 使用浏览器+代理访问 18comic.vip，登录得到AVS
2. 使用如下代码：
```python
import os
import sys
import jmcomic  # 导入此模块，需要先安装.


def get_option():
    option = jmcomic.JmOption.construct({
        'client': {
            'domain': ['18comic.vip'],
            'postman': {
                'meta_data': {
                    'proxies': jmcomic.ProxyBuilder.v2ray_proxy(),
                    'cookies': {
                        'AVS': '???????'
                    }
                }
            }
        },
        'dir_rule': {
            'base_dir': './download',
            'rule': os.environ.get('DIR_RULE', 'Bd_Aauthor_Atitle_Pindextitle')
        },
        'download': {
            'threading': {
                'batch_count': int(os.environ.get('BATCH_COUNT', 10))
            }
        }
    })

    return option


jm_option = get_option()
jmcomic.download_album([400511], option=jm_option)

```

**Comment by Lin-Guanguo** [comment]
加上 domain 参数, 能成功了. 不过多次尝试是概率成功, 还在试试看能不能稳定复现

**Comment by hect0x7** [comment]
固定代理、AVS、域名，跑了100次测试，成功:失败 = 69:31，挺玄学的🤣
