### ISSUE TITLE
请问有无办法只下载封面（或者限制只下载第一页）呢

### ISSUE THREAD

**Issue by lpf1143** [hect0x7/JMComic-Crawler-Python#181]
然后直接将所有的封面按漫画命名保存在一个文件夹下，不设分级文件夹

**Comment by hect0x7** [comment]
可以的，按照如下步骤：

1. option配置：
```yml
dir_rule:
  rule: Bd
  base_dir: 目标文件夹路径
```

2. python代码：
```python
from jmcomic import *


def init():
    # 只下载第一页
    class MyDownloader(JmDownloader):

        def do_filter(self, detail: DetailEntity):
            if detail.is_photo():
                return detail[:1]

            return super().do_filter(detail)

    # 让第一页的图片的文件名 = 漫画的标题
    class MyOption(JmOption):

        def decide_image_filename(self, image: JmImageDetail) -> str:
            if image.index == 1:
                return image.from_photo.from_album.name

            return super().decide_image_filename(image)

    JmModuleConfig.CLASS_DOWNLOADER = MyDownloader
    JmModuleConfig.CLASS_OPTION = MyOption


# 准备步骤，自定义替换了一些下载组件
init()

# 下面就正常使用下载api即可
op = JmOption.default()
op.download_album([123, 456])
```

效果如下：
![image](https://github.com/hect0x7/JMComic-Crawler-Python/assets/93357912/192f50c3-a38f-40f6-9445-534c11cd0356)

**Comment by lpf1143** [comment]
非常感谢！自己改了改现在能把收藏的封面全扒下来了。不过还是有一些小问题，有些下载会返回FileNotFoundError或者是OSError

`2023-12-13 19:50:52:【photo.after】章节下载完成: [481404] (246934[64/67])
2023-12-13 19:50:52:【image.after】图片下载完成: 479421/00001.webp [1/29], [https://cdn-msp.18comic.vip/media/photos/479421/00001.webp] → [C:/Users/xxx/Documents/jmcomic/bysa/(C102) [绅士仓库汉化] [FRAC (もとみやみつき)] メイドトリップ (オリジナル) [DL版].webp]
2023-12-13 19:50:52:【photo.after】章节下载完成: [479421] (479421[1/1])
2023-12-13 19:50:52:【album.after】本子下载完成: [479421]
2023-12-13 19:50:52:【html】https://18comic.vip/album/457664
Exception in thread Thread-688:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\xxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\jmcomic\jm_downloader.py", line 81, in <lambda>
    apply=lambda image: self.download_by_image_detail(image, client),
  File "C:\Users\xxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\jmcomic\jm_downloader.py", line 105, in download_by_image_detail
    decode_image=decode_image,
  File "C:\Users\xxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\jmcomic\jm_client_interface.py", line 271, in download_by_image_detail
    decode_image=decode_image,
  File "C:\Users\xxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\jmcomic\jm_client_interface.py", line 256, in download_image
    return self.save_image_resp(decode_image, img_save_path, img_url, resp, scramble_id)
  File "C:\Users\xxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\jmcomic\jm_client_interface.py", line 260, in save_image_resp
    resp.transfer_to(img_save_path, scramble_id, decode_image, img_url)
  File "C:\Users\xxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\jmcomic\jm_client_interface.py", line 81, in transfer_to
    path,
  File "C:\Users\xxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\jmcomic\jm_toolkit.py", line 757, in decode_and_save
    cls.save_image(img_decode, decoded_save_path)
  File "C:\Users\xxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\jmcomic\jm_toolkit.py", line 709, in save_image
    image.save(filepath)
  File "C:\Users\xxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\PIL\Image.py", line 2429, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/xxx/Documents/jmcomic/bysa/露出導演 / 想看妳露出羞恥的模樣 [甜米らくれ] 露出女子高生×映画男子 恥じらう君が見たいんだ.webp'

2023-12-13 19:50:53:【photo.after】章节下载完成: [496057] (246934[67/67])
Exception in thread Thread-690:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\xxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\jmcomic\jm_downloader.py", line 81, in <lambda>
    apply=lambda image: self.download_by_image_detail(image, client),
  File "C:\Users\xxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\jmcomic\jm_downloader.py", line 105, in download_by_image_detail
    decode_image=decode_image,
  File "C:\Users\xxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\jmcomic\jm_client_interface.py", line 271, in download_by_image_detail
    decode_image=decode_image,
  File "C:\Users\xxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\jmcomic\jm_client_interface.py", line 256, in download_image
    return self.save_image_resp(decode_image, img_save_path, img_url, resp, scramble_id)
  File "C:\Users\xxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\jmcomic\jm_client_interface.py", line 260, in save_image_resp
    resp.transfer_to(img_save_path, scramble_id, decode_image, img_url)
  File "C:\Users\xxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\jmcomic\jm_client_interface.py", line 81, in transfer_to
    path,
  File "C:\Users\xxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\jmcomic\jm_toolkit.py", line 757, in decode_and_save
    cls.save_image(img_decode, decoded_save_path)
  File "C:\Users\xxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\jmcomic\jm_toolkit.py", line 709, in save_image
    image.save(filepath)
  File "C:\Users\xxx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\PIL\Image.py", line 2429, in save
    fp = builtins.open(filename, "w+b")
OSError: [Errno 22] Invalid argument: 'C:/Users/xxx/Documents/jmcomic/bysa/[葱鱼个人呢汉化] [ろうか] 今日、 泊めてくれませんか? [中国翻訳] [DL版].webp'`

**Comment by hect0x7** [comment]
噢这是因为标题里存在特殊字符不能作为文件夹名

**Comment by hect0x7** [comment]
改动以下内容即可
```python
# 让第一页的图片的文件名 = 漫画的标题
class MyOption(JmOption):

    def decide_image_filename(self, image: JmImageDetail) -> str:
        if image.index == 1:
            name = image.from_photo.from_album.name # 改这里
            return fix_windir_name(name)

        return super().decide_image_filename(image)


```

**Comment by CCYellowStar2** [comment]
可是第一页也不是封面啊

**Comment by hect0x7** [comment]
> 可是第一页也不是封面啊

如果要下载封面：
```python
from jmcomic import JmOption, JmModuleConfig

op = JmOption.default()
cl = op.new_jm_client()

id_list = [245959]


def download_avatar(album_id):
    """
    下载封面
    """
    url = f'https://{JmModuleConfig.DOMAIN_IMAGE_LIST[0]}/media/albums/{album_id}.jpg'
    cl.download_image(url, f'./{album_id}.jpg', decode_image=False)


for aid in id_list:
    download_avatar(aid)
```

**Comment by hect0x7** [comment]
其实禁漫封面没有做加密，直接用requests库爬虫都行

**Comment by hect0x7** [comment]
请求失败的原因是域名配置不对
```
[2024-07-25 07:33:39] [MainThread]:【api】https://jm-comic2.cc/album?id=592111
```
这个域名是网页的，不能被使用移动端api请求。建议直接移除配置项 client.domain

**Comment by hect0x7** [comment]
还有不清楚的建议贴一下你的option配置文件

**Comment by hect0x7** [comment]
从这个判断，可能是你的ip被cf拦截了，可以换个代理试试
```
请求不是json格式，强制重试！响应文本: xxx
```

**Comment by hect0x7** [comment]
禁漫服务器不是很稳定，能用就行，失败的就换ip重试
