### ISSUE TITLE
在'趣味用法：测试你的ip可以访问哪些禁漫域名'中出现NameError: name 'AdvancedDict' is not defined

### ISSUE THREAD

**Issue by xiank1** [hect0x7/JMComic-Crawler-Python#221]
Traceback (most recent call last):
  File "D:\jmdownload\jmdownload\测试.py", line 5, in <module>
    from jmcomic import *
  File "C:\ProgramData\anaconda3\lib\site-packages\jmcomic\__init__.py", line 7, in <module>
    from .api import *
  File "C:\ProgramData\anaconda3\lib\site-packages\jmcomic\api.py", line 1, in <module>
    from .jm_downloader import *
  File "C:\ProgramData\anaconda3\lib\site-packages\jmcomic\jm_downloader.py", line 1, in <module>
    from .jm_option import *
  File "C:\ProgramData\anaconda3\lib\site-packages\jmcomic\jm_option.py", line 1, in <module>
    from .jm_client_impl import *
  File "C:\ProgramData\anaconda3\lib\site-packages\jmcomic\jm_client_impl.py", line 3, in <module>
    from .jm_client_interface import *
  File "C:\ProgramData\anaconda3\lib\site-packages\jmcomic\jm_client_interface.py", line 1, in <module>
    from .jm_toolkit import *
  File "C:\ProgramData\anaconda3\lib\site-packages\jmcomic\jm_toolkit.py", line 356, in <module>
    class JmPageTool:
  File "C:\ProgramData\anaconda3\lib\site-packages\jmcomic\jm_toolkit.py", line 475, in JmPageTool
    def parse_api_to_search_page(cls, data: AdvancedDict) -> JmSearchPage:
NameError: name 'AdvancedDict' is not defined

**Comment by hect0x7** [comment]
更新下commonX
```sh
pip install commonX -U
```

**Comment by xiank1** [comment]
十分感谢，已经解决了
