### ISSUE TITLE
[Bug] 好像失效了

### ISSUE THREAD

**Issue by nakamiv** [hect0x7/JMComic-Crawler-Python#278]
### 注意事项

- [X] 提ISSUE前，请确认你已经在GitHub Issues和Discussions里搜索过类似的问题，并且没找到想要的答案。
- [X] GitHub Actions问题请到置顶的Issue反馈。

### 发生Bug时，你的使用方式？

Python代码

### 你是否在禁漫官方网页或APP，验证过相应的功能是正常的？

测试过，禁漫官方功能正常

### option配置+源码/命令

jmcomic p624806
[2024-08-26 14:09:00] [MainThread]:【command_line】start downloading...
- using option: [D:\myoption.yml]
to be downloaded:
- album: []
- photo: ['624806']
[2024-08-26 14:09:00] [MainThread]:【plugin.invoke】调用插件: [login]
[2024-08-26 14:09:00] [MainThread]:【api】https://www.jmapidestiny.xyz/setting
[2024-08-26 14:09:00] [MainThread]:【plugin.exception】插件 [login] 调用失败，异常信息: [{"code":400,"data":[],"errorMsg":"Not legal."}]
Traceback (most recent call last):
  File "c:\program files\python\lib\site-packages\jmcomic\jm_option.py", line 546, in call_all_plugin
    self.invoke_plugin(pclass, kwargs, extra, pinfo)
  File "c:\program files\python\lib\site-packages\jmcomic\jm_option.py", line 585, in invoke_plugin
    self.handle_plugin_jmcomic_exception(e, pinfo, kwargs, plugin, pclass)
  File "c:\program files\python\lib\site-packages\jmcomic\jm_option.py", line 625, in handle_plugin_jmcomic_exception
    raise e
  File "c:\program files\python\lib\site-packages\jmcomic\jm_option.py", line 577, in invoke_plugin
    plugin.invoke(**kwargs)
  File "c:\program files\python\lib\site-packages\jmcomic\jm_plugin.py", line 122, in invoke
    client = self.option.build_jm_client(impl=impl)
  File "c:\program files\python\lib\site-packages\common\util\decorator_util.py", line 63, in func_exec
    attr = func(*args, **kwargs)
  File "c:\program files\python\lib\site-packages\jmcomic\jm_option.py", line 386, in build_jm_client
    return self.new_jm_client(**kwargs)
  File "c:\program files\python\lib\site-packages\jmcomic\jm_option.py", line 445, in new_jm_client
    client: AbstractJmClient = clazz(
  File "c:\program files\python\lib\site-packages\jmcomic\jm_client_impl.py", line 32, in __init__
    self.after_init()
  File "c:\program files\python\lib\site-packages\jmcomic\jm_client_impl.py", line 1007, in after_init
    self.ensure_have_cookies()
  File "c:\program files\python\lib\site-packages\jmcomic\jm_client_impl.py", line 1019, in ensure_have_cookies
    self['cookies'] = self.get_cookies()
  File "c:\program files\python\lib\site-packages\common\util\decorator_util.py", line 63, in func_exec
    attr = func(*args, **kwargs)
  File "c:\program files\python\lib\site-packages\jmcomic\jm_client_impl.py", line 1023, in get_cookies
    resp = self.setting()
  File "c:\program files\python\lib\site-packages\jmcomic\jm_client_impl.py", line 807, in setting
    resp = self.req_api('/setting')
  File "c:\program files\python\lib\site-packages\jmcomic\jm_client_impl.py", line 911, in req_api
    self.require_resp_success(resp, url)
  File "c:\program files\python\lib\site-packages\jmcomic\jm_client_impl.py", line 954, in require_resp_success
    resp.require_success()
  File "c:\program files\python\lib\site-packages\jmcomic\jm_client_interface.py", line 42, in require_success
    ExceptionTool.raises_resp(self.error_msg(), self)
  File "c:\program files\python\lib\site-packages\jmcomic\jm_exception.py", line 123, in raises_resp
    cls.raises(
  File "c:\program files\python\lib\site-packages\jmcomic\jm_exception.py", line 100, in raises
    raise e
jmcomic.jm_exception.ResponseUnexpectedException: {"code":400,"data":[],"errorMsg":"Not legal."}
[2024-08-26 14:09:00] [Thread-1]:【api】https://www.jmapidestiny.xyz/setting
[2024-08-26 14:09:01] [Thread-1]:【dler.exception】JmDownloader Exit with exception: (<class 'jmcomic.jm_exception.ResponseUnexpectedException'>, ResponseUnexpectedException('{"code":400,"data":[],"errorMsg":"Not legal."}', {'resp': <jmcomic.jm_client_interface.JmApiResp object at 0x0000027459EBCD00>}))
Exception in thread Thread-1:
Traceback (most recent call last):
  File "c:\program files\python\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "c:\program files\python\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "c:\program files\python\lib\site-packages\jmcomic\api.py", line 36, in <lambda>
    apply_each_obj_func=lambda aid: download_api(aid,
  File "c:\program files\python\lib\site-packages\jmcomic\api.py", line 87, in download_photo
    photo = dler.download_photo(jm_photo_id)
  File "c:\program files\python\lib\site-packages\jmcomic\jm_downloader.py", line 76, in download_photo
    client = self.client_for_photo(photo_id)
  File "c:\program files\python\lib\site-packages\jmcomic\jm_downloader.py", line 184, in client_for_photo
    return self.option.build_jm_client()
  File "c:\program files\python\lib\site-packages\common\util\decorator_util.py", line 63, in func_exec
    attr = func(*args, **kwargs)
  File "c:\program files\python\lib\site-packages\jmcomic\jm_option.py", line 386, in build_jm_client
    return self.new_jm_client(**kwargs)
  File "c:\program files\python\lib\site-packages\jmcomic\jm_option.py", line 445, in new_jm_client
    client: AbstractJmClient = clazz(
  File "c:\program files\python\lib\site-packages\jmcomic\jm_client_impl.py", line 32, in __init__
    self.after_init()
  File "c:\program files\python\lib\site-packages\jmcomic\jm_client_impl.py", line 1007, in after_init
    self.ensure_have_cookies()
  File "c:\program files\python\lib\site-packages\jmcomic\jm_client_impl.py", line 1019, in ensure_have_cookies
    self['cookies'] = self.get_cookies()
  File "c:\program files\python\lib\site-packages\common\util\decorator_util.py", line 63, in func_exec
    attr = func(*args, **kwargs)
  File "c:\program files\python\lib\site-packages\jmcomic\jm_client_impl.py", line 1023, in get_cookies
    resp = self.setting()
  File "c:\program files\python\lib\site-packages\jmcomic\jm_client_impl.py", line 807, in setting
    resp = self.req_api('/setting')
  File "c:\program files\python\lib\site-packages\jmcomic\jm_client_impl.py", line 911, in req_api
    self.require_resp_success(resp, url)
  File "c:\program files\python\lib\site-packages\jmcomic\jm_client_impl.py", line 954, in require_resp_success
    resp.require_success()
  File "c:\program files\python\lib\site-packages\jmcomic\jm_client_interface.py", line 42, in require_success
    ExceptionTool.raises_resp(self.error_msg(), self)
  File "c:\program files\python\lib\site-packages\jmcomic\jm_exception.py", line 123, in raises_resp
    cls.raises(
  File "c:\program files\python\lib\site-packages\jmcomic\jm_exception.py", line 100, in raises
    raise e
jmcomic.jm_exception.ResponseUnexpectedException: {"code":400,"data":[],"errorMsg":"Not legal."}

**Comment by hect0x7** [comment]
又要换域名了

**Comment by hect0x7** [comment]
你可以先自己试试配置域名，使用配置文件
 ```
client:
  domain:
    api: 
      - jmxxx1.com
      - jmxxx2.com
```

**Comment by hect0x7** [comment]
目前可用的域名配置：
```yml
client:
  domain:
    api:
      - www.jmapiproxyxxx.one
      - www.jmeadpoolcdn.one
      - www.jmeadpoolcdn.life
```

**Comment by Smile8848** [comment]
> 目前可用的域名配置：
> 
> ```yaml
> client:
>   domain:
>     api:
>       - www.jmapiproxyxxx.one
>       - www.jmeadpoolcdn.one
>       - www.jmeadpoolcdn.life
> ```

测试可用

**Comment by hect0x7** [comment]
jmcomic已更新最新线路，升级到v2.5.19可以免去上述配置
